### ISSUE TITLE
[Bug]: Middleware context.response object missing most of it params

### ISSUE THREAD

**Issue by kirillbashtenko** [web-infra-dev/modern.js#5687]
### 版本信息

```sh
System:
    OS: macOS 13.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 199.65 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 124.0.6367.79
    Safari: 17.4.1
  npmPackages:
    @modern-js/app-tools: 2.49.1 => 2.49.1 
    @modern-js/eslint-config: 2.49.1 => 2.49.1 
    @modern-js/plugin-server: 2.49.1 => 2.49.1 
    @modern-js/runtime: 2.49.1 => 2.49.1 
    @modern-js/tsconfig: 2.49.1 => 2.49.1
```

### 问题详情

Hello, it looks like in the latest version, Middleware `context.response` is missing most of the declared things, we can't set cookies or do anything else.

If you try to console log it this is all that you will see.
```
{ private_overrided: false, locals: {} }
``` 

### 复现链接

https://github.com/kirillbashtenko/modernjs-middleware-issue

### 复现步骤

1 pnpm install
2 pnpm start
3 try console.log context.response in middleware

**Comment by yimingjfe** [comment]
Thanks for your feedback, we have reproduced the issue and will fix it as soon as possible.

**Comment by GiveMe-A-Name** [comment]
Got it, we will fix it recently

**Comment by GiveMe-A-Name** [comment]
it  fixed by https://github.com/web-infra-dev/modern.js/pull/5700

**Comment by kirillbashtenko** [comment]
@GiveMe-A-Name @yimingjfe Unfortunately still reproducible.

PS: Reproduce link update to **2.49.3** version. Please take a look.

**Comment by GiveMe-A-Name** [comment]
@kirillbashtenko  
You can set cookie by using `context.response.cookie.set(key, value)`, even though you can't print it.
The context.response is implements like this: 
```ts
class BaseResponse {
  get cookie() {
    return ..
  }
}

const baseRes = new BaseResponse()
```
In `node.js`, we can't print `baseRes` properties. But the cookie attributes is exists truly.

**Comment by kirillbashtenko** [comment]
@GiveMe-A-Name Indeed, my bad, thank you, i'm closing this one.
